name: XpCommands
main: me.uksspy.XpCommands.XpCommands
version: 1.0
description: Configure certain commands to require xp to execute.
softdepend: [PlaceholderAPI]
commands:
   xpc:
     description: Master XpCommands command.